export const GET_BURGER = 'GET_BURGER';

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FAIL_FETCH_INGREDIENTS = 'FAIL_FETCH_INGREDIENTS';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const PLACE_ORDER_INIT = 'PLACE_ORDER_INIT';
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
