export const GET_BURGER = 'GET_BURGER';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FAIL_FETCH_INGREDIENTS = 'FAIL_FETCH_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FAIL_FETCH_ORDERS = 'FAIL_FETCH_ORDERS';
